apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: blog
build:
  local:
    push: false
  artifacts:
    - image: marcosmartinez7/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.js'
            dest: .
    - image: marcosmartinez7/comments
      context: comment-service
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '*.js'
            dest: .
    - image: marcosmartinez7/event-bus
      context: event-bus
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '*.js'
            dest: .
    - image: marcosmartinez7/moderation
      context: moderation-service
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '*.js'
            dest: .
    - image: marcosmartinez7/posts
      context: post-service
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '*.js'
            dest: .
    - image: marcosmartinez7/query
      context: query-service
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '*.js'
            dest: .
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
