apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: auth

build:
  #local:
  # push: false
  googleCloudBuild:
    projectId: ticketing-dev-340521
  artifacts:
    - image: us.gcr.io/ticketing-dev-340521/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "auth/src/**/*.ts"
            dest: .
    - image: us.gcr.io/ticketing-dev-340521/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "**/*.js"
            dest: .
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
